<a href="https://colab.research.google.com/github/DrLennon666/DAT4-students/blob/master/whatispytroch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

WHAT IS PYTORCH?

It’s a Python-based scientific computing package targeted at two sets of audiences:

A replacement for NumPy to use the power of GPUs
a deep learning research platform that provides maximum flexibility and speed
Getting Started

**Tensors**

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [0]:
from __future__ import print_function
import torch

NOTE

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

The next cell we show how to construct an empty tensor.

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[1.4892e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.1657e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [0]:
x = torch.empty(5, 3)
print(x)

Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5,3) #5 rows, 3 columns.
print(x)

tensor([[0.3275, 0.8668, 0.9477],
        [0.9231, 0.0662, 0.3769],
        [0.2354, 0.4352, 0.5003],
        [0.9434, 0.0414, 0.3469],
        [0.2134, 0.5565, 0.3561]])


Construct a matrix filled zeros and of dtype long:


In [5]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [11]:
x= torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [12]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size as ones x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4938,  0.0683,  1.5487],
        [ 2.2020, -1.1095, -0.2831],
        [ 0.2488, -1.3457,  2.0103],
        [-0.0178,  0.2657,  1.3322],
        [ 0.3919, -0.1250,  0.1579]])


Get its size:

In [14]:
x.size()

torch.Size([5, 3])

torch.Size is in fact a tuple, so it supports all tuple operations.

**Operations**

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [16]:
y = torch.rand(5,3)
print(y)
print(x)
print(x+y) # this performs elementwise addition

tensor([[0.9921, 0.5185, 0.6631],
        [0.4653, 0.6586, 0.7786],
        [0.5036, 0.8762, 0.7100],
        [0.8471, 0.9079, 0.8328],
        [0.5360, 0.8683, 0.4260]])
tensor([[-0.4938,  0.0683,  1.5487],
        [ 2.2020, -1.1095, -0.2831],
        [ 0.2488, -1.3457,  2.0103],
        [-0.0178,  0.2657,  1.3322],
        [ 0.3919, -0.1250,  0.1579]])
tensor([[ 0.4983,  0.5868,  2.2118],
        [ 2.6673, -0.4509,  0.4955],
        [ 0.7524, -0.4695,  2.7202],
        [ 0.8293,  1.1736,  2.1651],
        [ 0.9279,  0.7433,  0.5838]])


Addition: syntax 2

In [17]:
torch.add(x,y)

tensor([[ 0.4983,  0.5868,  2.2118],
        [ 2.6673, -0.4509,  0.4955],
        [ 0.7524, -0.4695,  2.7202],
        [ 0.8293,  1.1736,  2.1651],
        [ 0.9279,  0.7433,  0.5838]])

Addition: providing an output tensor as argument

In [18]:
result = torch.empty(5,3)  #create and empty tensor of shape 5x3
torch.add(x,y, out=result) # add tensors x and y then save the sum to the empty result tensor
print(result)

tensor([[ 0.4983,  0.5868,  2.2118],
        [ 2.6673, -0.4509,  0.4955],
        [ 0.7524, -0.4695,  2.7202],
        [ 0.8293,  1.1736,  2.1651],
        [ 0.9279,  0.7433,  0.5838]])


Addition: in-place

In [21]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.4983,  0.5868,  2.2118],
        [ 2.6673, -0.4509,  0.4955],
        [ 0.7524, -0.4695,  2.7202],
        [ 0.8293,  1.1736,  2.1651],
        [ 0.9279,  0.7433,  0.5838]])


**NOTE**

Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [25]:
print(x[:, 1]) # access all rows and col 1
print('\n',x)

tensor([ 0.0683, -1.1095, -1.3457,  0.2657, -0.1250])

 tensor([[-0.4938,  0.0683,  1.5487],
        [ 2.2020, -1.1095, -0.2831],
        [ 0.2488, -1.3457,  2.0103],
        [-0.0178,  0.2657,  1.3322],
        [ 0.3919, -0.1250,  0.1579]])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:



In [26]:
x = torch.randn(4, 4) # create random 4x4 tensor
y = x.view(16)
z = x.view(-1,8) # the size -1 is inferred from other dimenstions. i.e. it is 2 in this case as 2*8=16
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number


In [27]:
x = torch.randn(1) # create a 0d tensor
print(x)
print(x.item())
type(x.item())

tensor([-0.1124])
-0.11242961138486862


float

Other tensor operations can be found [here](https://pytorch.org/docs/stable/torch.html)

**NumPy Bridge**

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

**Converting a Torch Tensor to a NumPy Array**

In [28]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

recall: the `_` changed the tensor in-place. a and b share the same memory allocation since both are on the CPU, hence updating one changes both. 

In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


**Converting NumPy Array to Torch Tensor**

See how changing the np array changed the Torch Tensor automatically

`.from_numpy` creates a torch tensor
a and b share same memory allocation

In [34]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

**CUDA Tensors**

Tensors can be moved onto any device using the `.to` method.

In [38]:
# Run this cell only if CUDA is available
# We will use torch.device object to move tensors in and out of GPU

print(torch.cuda.is_available()) # check if CUDA is available on machine

if torch.cuda.is_available():
  device = torch.device('cuda') # a CUDA device object
  y = torch.ones_like(x, device=device) # directly create a tensor on GPU
  x = x.to(device) # or just use strings such as '.to('cuda')'
  z = x + y
  print(z)
  print(z.to('cpu', torch.double)) # `.to` can also change dtype togheter

True
tensor([0.8876], device='cuda:0')
tensor([0.8876], dtype=torch.float64)


In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!